FashionShop/Controllers/ReviewController.cs
using FashionShop.Models;
using FashionShop.Models.EF;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Controllers
{
    [Authorize]
    public class ReviewController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Review
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult _Review(int productId)
        {
            ViewBag.ProductId = productId;
            var item = new ReviewProduct();
            if(User.Identity.IsAuthenticated)
            {
                var userStore = new UserStore<ApplicationUser>(new ApplicationDbContext());
                var userManager = new UserManager<ApplicationUser>(userStore);
                var user = userManager.FindByName(User.Identity.Name);
                if(user != null)
                {
                    item.Email = user.Email;
                    item.FullName = user.Fullname;
                    item.UserName = user.UserName;
                }
                return PartialView(item);
            }
            return PartialView();
        }

        [AllowAnonymous]
        public ActionResult Load_Review(int productId)
        {
            var item = db.Reviews.Where(x => x.ProductId == productId).OrderByDescending(x => x.Id).ToList();
            ViewBag.Count = item.Count;
            return PartialView(item);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult PostReview(ReviewProduct req)
        {
            if(ModelState.IsValid)
            {
                req.CreatedDate = DateTime.Now;
                db.Reviews.Add(req);
                db.SaveChanges();
                return Json(new { Success = true });
            }
            return Json(new { Success = false });
        }
    }
}

FashionShop/Views/Review/Load_Review.cshtml
@model IEnumerable<FashionShop.Models.EF.ReviewProduct>

<div class="tab_title reviews_title">
    <h4>Đánh giá (@ViewBag.Count)</h4>
</div>

<!-- User Review -->
@if (Model != null && Model.Any())
{
    foreach (var item in Model)
    {
        <div class="user_review_container d-flex flex-column flex-sm-row">
            <div class="user">
                <div class="user_pic"></div>
                <div class="user_rating">
                    <ul class="star_rating">
                        @Html.Raw(FashionShop.Models.common.Common.HtmlRate(item.Rate))
                    </ul>
                </div>
            </div>
            <div class="review">
                <div class="review_date">@item.CreatedDate.ToString("dd MM yyyy")</div>
                <div class="user_name">@item.FullName</div>
                <p>@item.Content</p>
            </div>
        </div>

        @*<div class="user_review_container d-flex flex-column flex-sm-row">
            <div class="user">
                <div class="user_pic"></div>
                <div class="user_rating">
                    <ul class="star_rating">
                        @Html.Raw(FashionShop.Models.common.Common.HtmlRate(item.Rate))
                    </ul>
                </div>
            </div>
            <div class="review">
                <div class="review_date">@item.CreatedDate.ToString("dd MM yyyy")</div>
                <div class="user_name">@item.FullName</div>
                <p>@item.Content</p>
            </div>
        </div>*@
    }


    <!-- User Review -->


}

FashionShop/Views/Review/_Review.cshtml
@model FashionShop.Models.EF.ReviewProduct

<div class="add_review">
    @using (Ajax.BeginForm("PostReview", "Review", new AjaxOptions
    {
        HttpMethod = "POST",
        UpdateTargetId = "load_review",
        OnSuccess = "ONSuccessRE",
        OnFailure = "OnfailureRE",
        OnBegin = "OnBeginRE"
    }, new { @Id = "review_form" }))
    {
        <script>
            function OnBeginRE() {
                $('#review_submit').attr("disabled", "disabled");
                $('#load_send').html('<h2>Đang gửi</h2>');
            }
            function ONSuccessRE(res) {
                if (res.Success) {
                    $("#review_form")[0].reset();
                }
            }
        </script>
        @Html.AntiForgeryToken()
        @*<form id="review_form" action="post">*@

<div>
    <h1>Đánh giá sản phẩm</h1>
    @Html.TextBoxFor(x => x.FullName, new { @class = "form_input input_name", @placeholder = "Tên khách hàng*", @id = "review_name" })
    @Html.TextBoxFor(x => x.Email, new { @class = "form_input input_email", @placeholder = "Email*", @id = "review_email" })
    @Html.HiddenFor(x => x.UserName)
    @Html.HiddenFor(x => x.ProductId, new { @Value = ViewBag.ProductId })
    <input type="text" id="txtRate" name="Rate" value="4" style="visibility: hidden;"/>
    @*<input id="review_name" class="form_input input_name" type="text" name="name" placeholder="Name*" required="required" data-error="Name is required.">*@
    @*<input id="review_email" class="form_input input_email" type="email" name="email" placeholder="Email*" required="required" data-error="Valid email is required.">*@
</div>
        <div>
            <h1>Đánh giá:</h1>
            <ul class="user_star_rating">
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
            </ul>
            @Html.TextAreaFor(x => x.Content, new { @class = "input_review", @rows = "4", @placeholder = "Đánh giá của bạn" })
            @*<textarea id="review_message" class="input_review" name="message" placeholder="Your Review" rows="4" required data-error="Please, leave us a review."></textarea>*@
        </div>
        <div class="text-left text-sm-right">
            <button id="review_submit" type="submit" class="red_button review_submit_btn trans_300" value="Gửi">Gửi</button>
        </div>
        @*</form>*@
    }
</div>