FashionShop/Models/EF/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FashionShop.Models.EF
{
    [Table("Tb_Category")]
    public class Category: CommonAbstract
    {
        public Category()
        {
            this.News = new HashSet<News>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Tên danh mục không được để trống!!!")]
        [StringLength(150)]
        public string Title { get; set; }
        public string Alias { get; set; }
        //[StringLength(150)]

        //public string TypeCode { get; set; }
        //public string Link { get; set; }
        public string Description { get; set; }
        public int Position { get; set; }
        [StringLength(150)]
        public string SeoTitle { get; set; }
        [StringLength(150)]
        public string SeoDescription { get; set; }
        [StringLength(150)]
        public string SeoKeywords { get; set; }
        public bool IsActive { get; set; }

        public ICollection<News> News { get; set; }
        public ICollection<Posts> Posts { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }

    }
}

FashionShop/Areas/Admin/Controllers/CategoryController.cs
using FashionShop.Models;
using FashionShop.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, Staff")]
    public class CategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/Category
        public ActionResult Index()
        {
            var items = db.Categories;
            return View(items);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Category model)
        {
            if(ModelState.IsValid)
            {
                model.CreatedDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;
                model.Alias = FashionShop.Models.common.Filter.FilterChar(model.Title);
                db.Categories.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var item = db.Categories.Find(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category model)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Attach(model);
                model.ModifiedDate = DateTime.Now;
                model.Alias = FashionShop.Models.common.Filter.FilterChar(model.Title);
                db.Entry(model).Property(x => x.Title).IsModified = true;
                db.Entry(model).Property(x => x.Description).IsModified = true;
                db.Entry(model).Property(x => x.Alias).IsModified = true;
                db.Entry(model).Property(x => x.SeoDescription).IsModified = true;
                db.Entry(model).Property(x => x.SeoKeywords).IsModified = true;
                db.Entry(model).Property(x => x.SeoTitle).IsModified = true;
                db.Entry(model).Property(x => x.Position).IsModified = true;
                db.Entry(model).Property(x => x.ModifiedDate).IsModified = true;
                db.Entry(model).Property(x => x.ModifiedBy).IsModified = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = db.Categories.Find(id);
            if(item != null)
            {
                //var DeleteItem = db.Categories.Attach(item);
                db.Categories.Remove(item);
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

FashionShop/Areas/Admin/Views/Category/Add.cshtml
@model FashionShop.Models.EF.Category
@{
    ViewBag.Title = "Thêm danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader {
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/RevenueStatistical/index" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Category" class="nav-link">Danh mục</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Thêm</a>
        </li>
    </ul>
}

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thêm thông tin danh mục</h3>

            
        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Add", "Category", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <!-- your steps content here -->
                <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tên danh mục</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Tên danh mục" })
                        @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Mô tả</label>
                        @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Tiêu đề SEO</label>
                        @Html.TextAreaFor(x => x.SeoTitle, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Mô tả SEO</label>
                        @Html.TextAreaFor(x => x.SeoDescription, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Từ khóa SEO</label>
                        @Html.TextAreaFor(x => x.SeoKeywords, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <a href="/Admin/Category" class="btn btn-danger">Quay lại</a>
                        <button type="submit" class="btn btn-primary">Thêm</button>
                    </div>
                </div>
    
                }

            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

FashionShop/Areas/Admin/Views/Category/Edit.cshtml
@model FashionShop.Models.EF.Category
@{
    ViewBag.Title = "Cập nhật danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader {
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/RevenueStatistical/index" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Category" class="nav-link">Danh mục</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Cập nhật</a>
        </li>
    </ul>
}

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Cập nhật thông tin danh mục</h3>


        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Edit", "Category", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(x => x.Id)
                    <!-- your steps content here -->
                    <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Tên danh mục</label>
                            @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Tên danh mục" })
                            @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label for="exampleInputPassword1">Mô tả</label>
                            @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                        </div>

                        @*<div class="form-group">
                            <label for="exampleInputEmail1">No:</label>
                            @Html.TextBoxFor(x => x.Position, new { @class = "form-control", @Value = "1" })
                        </div>*@

                        <div class="form-group">
                            <label for="exampleInputPassword1">Tiêu đề SEO</label>
                            @Html.TextAreaFor(x => x.SeoTitle, new { @class = "form-control" })
                        </div>

                        <div class="form-group">
                            <label for="exampleInputPassword1">Mô tả SEO</label>
                            @Html.TextAreaFor(x => x.SeoDescription, new { @class = "form-control" })
                        </div>

                        <div class="form-group">
                            <label for="exampleInputPassword1">Từ khóa SEO</label>
                            @Html.TextAreaFor(x => x.SeoKeywords, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <a href="/Admin/Category" class="btn btn-danger">Quay lại</a>
                            <button type="submit" class="btn btn-primary">Sửa</button>
                        </div>
                    </div>

                }

            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

FashionShop/Areas/Admin/Views/Category/Index.cshtml
@model IEnumerable<FashionShop.Models.EF.Category>
    @{
        ViewBag.Title = "Category";
        Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    }

    @section naviheader {
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="/Admin/RevenueStatistical/index" class="nav-link">Trang chủ</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="/Admin/Category" class="nav-link">Danh mục</a>
            </li>
        </ul>
    }

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh mục</h3>

                <div class="card-tools">
                    <a href="/Admin/Category/Add" class="btn btn-primary">Thêm mới</a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên danh mục</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Any())
                        {
                            var i = 1;
                            foreach (var item in Model)
                            {
                                <tr id="trow_@item.Id">
                                    <td>@i</td>
                                    <td>@item.Title</td>
                                    <td>
                                        <a href="/Admin/Category/edit/@item.Id" class="btn btn-sm btn-primary">Sửa</a>
                                        <a href="#" data-id="@item.Id" class="btn btn-sm btn-danger btnDelete">Xóa</a>
                                    </td>
                                </tr>
                                i++;
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="4">Không có bản ghi nào!!!</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">

            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->


@section scripts {
    <script>
        $(document).ready(function () {
            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm('Bạn có chắc muốn xóa bản ghi này?');
                if (conf === true) {
                    $.ajax({
                        url: '/admin/category/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    });
                }
            })
        });
    </script>    
}