FashionShop/Models/EF/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FashionShop.Models.EF
{
    [Table("Tb_Contact")]
    public class Contact: CommonAbstract
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Tên không được để trống")]
        [StringLength(150, ErrorMessage = "Không được quá 150 kí tự")]
        public string Name { get; set; }
        [StringLength(150, ErrorMessage = "Không được quá 150 kí tự")]
        public string Email { get; set; }
        public string Website { get; set; }
        [StringLength(4000)]
        public string Message { get; set; }
        public bool Isread { get; set; }

    }
}

FashionShop/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, Staff")]
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

FashionShop/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact

        [HttpPost]
        public ActionResult SendMail(string name, string email, string message)
        {
            try
            {
                var fromEmail = System.Configuration.ConfigurationManager.AppSettings["Email"];
                var password = System.Configuration.ConfigurationManager.AppSettings["PasswordEmail"];
                var toEmail = System.Configuration.ConfigurationManager.AppSettings["EmailAdmin"];

                var subject = "Thông tin liên hệ từ khách hàng";
                var body = $"Tên: {name}\nEmail: {email}\nNội dung:\n{message}";

                var smtpClient = new SmtpClient("smtp.gmail.com")
                {
                    Port = 587,
                    Credentials = new NetworkCredential(fromEmail, password),
                    EnableSsl = true,
                };

                smtpClient.Send(fromEmail, toEmail, subject, body);

                TempData["SuccessMessage"] = "Gửi thành công! Chúng tôi sẽ phản hồi sớm.";
            }
            catch
            {
                TempData["ErrorMessage"] = "Có lỗi xảy ra khi gửi, vui lòng thử lại sau.";
            }
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

FashionShop/Controllers/HomeController.cs
using FashionShop.Models;
using FashionShop.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Partial_Subcribe()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Subcribe(Subcribe req)
        {
            if(ModelState.IsValid)
            {
                db.Subcribe.Add(new Subcribe { Email = req.Email, CreatedDate = DateTime.Now });
                db.SaveChanges();
                return Json(new { Success = true });
            }
            return View("Partial_Subcribe", req);
        }

        public ActionResult Chat()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Refresh()
        {
            var item = new StatisticalModel();
            ViewBag.Visitors_online = HttpContext.Application["Visitors_online"];
            var hn = HttpContext.Application["Today"];
            item.Today = HttpContext.Application["Today"].ToString();
            item.Yesterday = HttpContext.Application["Yesterday"].ToString();
            item.ThisWeek = HttpContext.Application["ThisWeek"].ToString();
            item.LastWeek = HttpContext.Application["LastWeek"].ToString();
            item.ThisMonth = HttpContext.Application["ThisMonth"].ToString();
            item.LastMonth = HttpContext.Application["LastMonth"].ToString();
            item.Total = HttpContext.Application["Total"].ToString();

            return PartialView(item);
        }


        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FashionShop/Controllers/MenuController.cs
using FashionShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuTop()
        {
            var items = db.Categories.OrderBy(x => x.Position).ToList();
            return PartialView("_MenuTop", items);
        }

        public ActionResult MenuProductCategory()
        {
            var items = db.ProductCategory.ToList();
            return PartialView("_MenuProductCategory", items);
        }

        public ActionResult MenuLeft(int? id)
        {
            if(id != null)
            {
                ViewBag.CateId = id;
            }
            var items = db.ProductCategory.ToList();
            return PartialView("_MenuLeft", items);
        }

        public ActionResult MenuArrivals()
        {
            var items = db.ProductCategory.ToList();
            return PartialView("_MenuArrivals", items);
        }
    }
}

FashionShop/Controllers/NewsController.cs
using FashionShop.Models;
using FashionShop.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Controllers
{
    public class NewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: News
        public ActionResult Index(int? page)
        {
            var pageSize = 10;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<News> items = db.News.OrderByDescending(x => x.CreatedDate);
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }

        public ActionResult Detail(int id)
        {
            var item = db.News.Find(id);
            return View(item);
        }

        public ActionResult Partial_News_Home()
        {
            var items = db.News.Take(3).ToList();
            return PartialView(items);
        }
    }
}

FashionShop/Controllers/ProductsController.cs
using FashionShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShop.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        public ActionResult Index()
        {
            var items = db.Product.ToList();
            return View(items);
        }

        public ActionResult Detail(string alias, int id)
        {
            var item = db.Product.Find(id);
            if(item != null)
            {
                db.Product.Attach(item);
                item.ViewCount = item.ViewCount + 1;
                db.Entry(item).Property(x => x.ViewCount).IsModified = true;
                db.SaveChanges();
            }

            var countReview = db.Reviews.Where(x => x.ProductId == id).Count();
            ViewBag.CountReview = countReview;
            return View(item);
        }
        public ActionResult ProductCategory(string alias, int id)
        {
            var items = db.Product.ToList();

            if (id > 0)
            {
                items = items.Where(x => x.ProductCategoryId == id).ToList();
            }
            var cate = db.ProductCategory.Find(id);
            if(cate != null)
            {
                ViewBag.CateName = cate.Title;
            }
            ViewBag.CateId = id;
            return View(items);
        }

        public ActionResult Partial_ItemsByCateId()
        {
            var items = db.Product.Where(x => x.IsHome && x.IsActive).Take(12).ToList();
            return PartialView(items);
        }

        public ActionResult Partial_ProductSales()
        {
            var items = db.Product.Where(x => x.IsSale && x.IsSale).Take(12).ToList();
            return PartialView(items);
        }

    }
}

FashionShop/Views/Home/About.cshtml
@{
    ViewBag.Title = "Khái quát";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Hiện tại trang này không được phát triển - Nguyễn Xuân Dương</p>

FashionShop/Views/Home/Chat.cshtml
@{
    ViewBag.Title = "Chat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/main_styles.css">

<style>
    
</style>
<div style="margin-top: 152px; width: 50%; height:623px; border: solid 5px green; border-radius: 1%; margin-left: 380px; padding:10px;">
    <div class="container" style="height: 94%; width: 100%; overflow-y: auto;">
        <ul id="contentMsg" style="font-size: 20px; word-wrap: break-word; overflow-wrap: break-word; white-space: normal;">
        </ul>
    </div>
    <div class="container" id="divChat" style="display: flex; justify-content: flex-end; padding-left: 0px; padding-right: 0px;">
        <input type="text" id="txtMessage" style="width: 100%; font-size: 20px;"/>
        <button class="btn btn-success" id="btnSend">Send</button>
    </div>
    @*<div class="container" id="divLogin">
        <input type="text" id="txtName" placeholder="Name" />
        <button class="btn btn-success" id="btnLogin">Login</button>
        <input type="hidden" id="hName" />
    </div>*@
</div>


@section scripts {
    <script>
        //function show() {
        //    $('#divLogin').hide();
        //    $('#divChat').show();
        //}
        //function hide() {
        //    $('#divLogin').show();
        //    $('#divChat').hide();
        //}
        $(function () {
            /*$('#divChat').hide();*/

            var chat = $.connection.chat;
            console.log(chat);
            loadClient(chat);
            $.connection.hub.start().done(function () {
                //$('#btnLogin').click(function () {
                //    var name = $("#txtName").val();
                //    chat.server.connect(name);
                //    //show();
                //});
                $('#btnSend').click(function () {
                    var msg = $('#txtMessage').val();
                    //var name = $('#hName').val();
                    var name = "@User.Identity.Name";
                    chat.server.message(name, msg);
                    $('#txtMessage').val('').focus();
                });
            });

        });

        function loadClient(chat) {
            chat.client.message = function (name, msg) {
                $('#contentMsg').append("<li style='max - width: 100 %; word - wrap: break-word; overflow - wrap: break-word; white - space: normal;'><strong>" + name + "</strong>: " + msg + "</li>");
                scrollToBottom();
            }
            chat.client.connect = function (name) {
                $('#hName').val(name);
            }
            
        }

        function scrollToBottom() {
            var chatContainer = document.querySelector(".container[style*='overflow-y: auto']");
            chatContainer.scrollTop = chatContainer.scrollHeight;
        }
    </script>    
}

FashionShop/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Liên hệ";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

@*<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>*@
<h1>Hiện tại trang này chưa được phát triển - Nguyễn Xuân Dương</h1>

FashionShop/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
}

<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/main_styles.css">


<div class="main_slider" style="background-image:url(/Content/assets/images/1.jpg)">
    <div class="container fill_height">
        <div class="row align-items-center fill_height">
            <div class="col">
                <div class="main_slider_content">
                    <h6>Bộ sưu tập Xuân Hè 2025</h6>
                    <h1>Được giảm giá tới 30%</h1>
                    <div class="red_button shop_now_button"><a href="/products">Mua ngay</a></div>
                </div>
            </div>
        </div>
    </div>
</div>

@Html.Action("MenuProductCategory", "Menu")
<!-- New Arrivals -->

<div class="new_arrivals">
    <div class="container">
        @Html.Action("MenuArrivals", "Menu")
    </div>
</div>

<!-- Deal of the week -->

<div class="deal_ofthe_week">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="deal_ofthe_week_img">
                    <img src="~/Content/assets/images/deal_ofthe_week.png" alt="">
                </div>
            </div>
            <div class="col-lg-6 text-right deal_ofthe_week_col">
                <div class="deal_ofthe_week_content d-flex flex-column align-items-center float-right">
                    <div class="section_title">
                        <h2>Ưu đãi trong tuần</h2>
                    </div>
                    <ul class="timer">
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="day" class="timer_num">03</div>
                            <div class="timer_unit">Ngày</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="hour" class="timer_num">15</div>
                            <div class="timer_unit">Giờ</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="minute" class="timer_num">45</div>
                            <div class="timer_unit">Phút</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="second" class="timer_num">23</div>
                            <div class="timer_unit">Giây</div>
                        </li>
                    </ul>
                    <div class="red_button deal_ofthe_week_button"><a href="/products">Mua ngay</a></div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Best Sellers -->

@Html.Action("Partial_ProductSales", "Products")

<div class="benefit">
    <div class="container">
        <div class="row benefit_row">
            <div class="col-lg-4 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-truck" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Miễn phí vận chuyển</h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-money" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Bảo hiểm vận chuyển</h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-undo" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Đổi trả trong 45 ngày</h6>
                    </div>
                </div>
            </div>
            @*<div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-clock-o" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Các ngày trong tuần</h6>
                    </div>
                </div>
            </div>*@
        </div>
    </div>
</div>

<!-- Blogs -->
@Html.Action("Partial_News_Home", "News")

FashionShop/Views/Home/Partial_Subcribe.cshtml
@model FashionShop.Models.EF.Subcribe

<!--<div class="newsletter">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="newsletter_text d-flex flex-column justify-content-center align-items-lg-start align-items-md-center text-center">
                    <h4>Newsletter</h4>
                    <p>Subscribe to our newsletter and get 20% off your first purchase</p>
                </div>
            </div>
            <div class="col-lg-6">
                @using (Ajax.BeginForm("Subcribe", "Home", new AjaxOptions
                {
                    OnBegin = "OnBeginSub",
                    OnSuccess = "OnSuccessSub",
                    OnFailure = "OnFailureSub"
                }))
                {
                    @Html.AntiForgeryToken()
                    <script>
                        function OnBeginSub() {

                        }
                        function OnSuccessSub(rs) {
                            if (rs.Success) {
                                alert("Ok");
                            }
                        }
                        function OnFailureSub(rs) {

                        }
                    </script>
                    <div class="newsletter_form d-flex flex-md-row flex-column flex-xs-column align-items-center justify-content-lg-end justify-content-center">-->
                        @*@Html.TextBoxFor(x => x.Email, new { @placeholder = "Your email", @type = "email", @required = "required" })*@
                        <!--<input id="newsletter_email" name="Email" type="email" placeholder="Your email" required="required" data-error="Valid email is required.">
                        <button id="newsletter_submit" type="submit" class="newsletter_submit_btn trans_300" value="Submit">subscribe</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>-->

FashionShop/Views/Home/Refresh.cshtml
@model FashionShop.Models.StatisticalModel
@if (Model != null)
            {
                <div class="statistical">
                    <table class="table">
                        <tr>
                            <td>Today</td>
                            <td>@Model.Today</td>
                        </tr>
                        <tr>
                            <td>Yesterday</td>
                            <td>@Model.Yesterday</td>
                        </tr>
                        <tr>
                            <td>This Week</td>
                            <td>@Model.ThisWeek</td>
                        </tr>
                        <tr>
                            <td>Customers online</td>
                            <td>@ViewBag.Visitors_online</td>
                        </tr>
                    </table>
                </div>
            }